### ISSUE TITLE
When I Search data on search bar., there was server error

### ISSUE THREAD

**Issue by innovatory-sincere-dev** [Lostovayne/Search-Products-With-Nextjs#1]

**Comment by Lostovayne** [comment]
Yes, what happens is that when doing the search, use the OpenAi Api to search for elements that match the Upstash Vector database and then returns the 5 elements of Postgresql, returns the elements that contain the search plus, the elements that contain the search, the elements that contain a high value in the vectors and are close to the value of the original search, which allows you to recommend similar articles, but the Free OpenAi quota apparently consumed it complete, so it shows the error.
